### ISSUE TITLE
MMDeploy exported models on Nvidia Jetson devices

### ISSUE THREAD

**Issue by RS00001** [open-mmlab/mmdeploy#122]
MMDeploy looks good and I had a few questions relating to deploying the output model on Nvidia EDGE device that I could not find on Readthedocs and Github pages. Apologies in advance if the questions are very basic in nature:

1. For Nvidia deployment, we will be selecting the TensorRT deployment option. So once I convert the model and get the SDK using my Mac, will I still need to install PyTorch on the Nvidia device that I want to use for inference? In other words, My Nvidia Device has the JetPack already installed, which includes TensorRT. So, can I simply 1) run the converted model, 2) need SDK with the converted model or 3) Need SDK, converted model and PyTorch + other installations suggested by MMPose?

2. I intend to use the model for pose detection using MMPose. Will there be any additional dependencies?

Update: I am planning to install the MMDeploy on my Mac and then get the updated model and SDK for my inference device which is Nvidia

**Comment by RunningLeon** [comment]
@RS00001 Hi, you could refer to the tutoria [how_to_install_mmdeploy_on_jetsons.md](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/tutorials/how_to_install_mmdeploy_on_jetsons.md) for the jetson device.

**Comment by RS00001** [comment]
@RunningLeon Thank you for the help. If you don't mind, could you please clarify this for me... Is this installation for deploying the MMDeploy generated model and SDK or to generate those? My intention is to generate the model and the SDK using my Mac and then get these deployed artifacts onto my Jetson Nano.

**Comment by RunningLeon** [comment]
> @RunningLeon Thank you for the help. If you don't mind, could you please clarify this for me... My intention is to generate the model and the SDK using my Mac and then get these deployed artifacts onto my Jetson Nano. So, above installation tutorial, is it for the device where I run inference or for the (Mac) device where I generate the SDK and my final model for TensorRT deployment?

@RS00001 Hi, how_to_install_mmdeploy_on_jetsons.md is for installing mmdeploy on Jetson Nano device. Once you have mmdeploy installed, you could do the conversion from PyTorch model to ONNX and then to TensorRT engine. With TensorRT engine, you can do the deployment.
Since you have to create TensorRT engine on your Jetson Nano device, you may have to install PyTorch as goes by the tutorial.
Once you have your TensorRT engine created, you can uninstall PyTorch and run inference for sure.

**Comment by RS00001** [comment]
Thanks @RunningLeon

**Comment by RS00001** [comment]
I followed the instructions and have spent whole day today trying to install the MMDEploy which includes installing MMCV. I tried both, installing from source and also the pre-compiled packages. In both, it is stuck at the stage "Building setup.py..." and even after hours there is no result. Could you please help

**Comment by tehkillerbee** [comment]
@RS00001 Some workarounds might be necessary necessary due to an old python 3.6 version. It sounds like you are running into similar issues as I did.

Maybe first run the following tool and list the versions of your OS and installed packages
```
https://github.com/jetsonhacks/jetsonUtilities
```

In (very) broad terms, I did the following:
* Make sure to update pip, setuptools, wheel, protobuf before installing remaining dependencies. Something along the following lines:
```
curl https://bootstrap.pypa.io/pip/3.6/get-pip.py -o get-pip.py
# dependencies
sudo apt-get purge cmake
sudo apt-get install curl ninja-build -y
sudo apt-get install python3-venv python3-dev python3-setuptools -y
sudo python3 get-pip.py
pip3 install testresources
pip3 install --upgrade setuptools wheel
sudo snap install cmake --classic
```
* If using virtual environment (Thats what I did), make sure to create it to inherit system-site-packages, otherwise tensorrt python package will be missing.
```
python3 -m venv venv-mmdet --system-site-packages
.. (Install all relevant dependencies in venv, including pip, setuptools, wheel.)
```
* Install older numpy (otherwise your torch probably wont work and will result in segfault when importing pytorch)
```
pip3 install numpy==1.19.4
```
* Update protobuf
```
pip3 install --upgrade protobuf
```
* Install Pytorch 1.10 +  suitable torchvision as follows
```
  # pytorch
  wget https://nvidia.box.com/shared/static/fjtbno0vpo676a25cgvuqc1wty0fkkg6.whl -O torch-1.10.0-cp36-cp36m-linux_aarch64.whl
  pip3 install torch-1.10.0-cp36-cp36m-linux_aarch64.whl
  # torchvision
  sudo apt-get install libjpeg-dev zlib1g-dev libpython3-dev libavcodec-dev libavformat-dev libswscale-dev
  sudo rm -r torchvision
  git clone --branch v0.11.0 https://github.com/pytorch/vision torchvision
  cd torchvision
  export BUILD_VERSION=0.11.1  # where 0.x.0 is the torchvision version  
  python3 setup.py install
  cd ../
```
* Install mmcv
```
# mmcv
pip3 uninstall mmcv-full
pip3 install mmcv-full==1.4.1 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.10.0/index.html
```
* Setup mmdeploy + dependencies
```
# mmdeploy + dependencies (OpenCV is assumed to be installed!)
sudo apt-get install libspdlog-dev -y
# misc mmdeploy/h5py dependencies
sudo apt-get install libhdf5-dev -y

* ppl_cv
```
cd ${PROJECT_DIR}/ppl.cv
rm -r cuda-build
#./build.sh x86_64
#./build.sh aarch64
./build.sh cuda
```

## h5py not directly supported by jetson and must be built/installed manually
# sudo env H5PY_SETUP_REQUIRES=0 pip3 install -U h5py==3.1.0
# as a workaround, we will install an earlier version that can build and install successfully
pip3 install h5py==2.9.0
# maybe do the following instead?
#sudo apt-get install pkd-config libhdf5-100 libhdf5-dev
#pip install versioned-hdf5 --no-cache-dir

## mmdeploy + SDK
```
cd ${PROJECT_DIR}/MMDeploy
git submodule update --init --recursive
pip install -e .
rm -r build
mkdir build -p && cd build
cmake .. \
  -DMMDEPLOY_BUILD_SDK=ON \
  -DCMAKE_CXX_COMPILER=g++ \
  -Dpplcv_DIR=${PROJECT_DIR}/ppl.cv/cuda-build/install/lib/cmake/ppl \
  -DMMDEPLOY_TARGET_DEVICES="cuda;cpu" \
  -DMMDEPLOY_TARGET_BACKENDS=trt \
  -DMMDEPLOY_CODEBASES=all
cmake --build . -- -j$(nproc) && cmake --install .
sudo ldconfig
```

# add MMDeploy_DIR to bashrc
```
echo -e 'export MMDeploy_DIR='${PROJECT_DIR}'/MMDeploy/build/install/lib/cmake/MMDeploy' >> ${HOME}/.bashrc
source ${HOME}/.bashrc
```

## mmdeploy examples
```
export LD_LIBRARY_PATH=${PROJECT_DIR}/MMDeploy/build/install/lib
cd ${PROJECT_DIR}/MMDeploy/build/install/example
rm -r build
mkdir build -p && cd build
cmake -DMMDeploy_DIR=${PROJECT_DIR}/MMDeploy/build/install/lib/cmake/MMDeploy ..
make all
```

**Comment by tehkillerbee** [comment]
With the above steps, inference does work (partially) on Jetson AGX. However, the output detections  from tensorrt does not match the output from pytorch...

**Comment by RS00001** [comment]
@tehkillerbee - got it, thanks. Btw, were you able to install it on your AGX with a higher Python and Pytorch version?

**Comment by tehkillerbee** [comment]
@RS00001 Sure, I used the latest(?) Pytorch 1.10.0 listed by Nvidia. I also used the latest mmdeploy, although with some modifications to build with TensorRT7.

**Comment by RS00001** [comment]
@tehkillerbee - did that work with python 3.7 or later?

**Comment by tehkillerbee** [comment]
@RS00001 I have only tested with 3.6

**Comment by RS00001** [comment]
@tehkillerbee - I am also trying with 3.6 and with the steps you provided. However, I am getting stuck at Torchvision installation. It is failing with a runtime error.

**Comment by tehkillerbee** [comment]
@RS00001 It looks like you are running out of RAM and the process was killed. I guess that makes sense since you are using a jetson nano 4G, whereas I'm using either 8 or 32GB platforms. Try increasing your swap and see if it helps.

**Comment by RS00001** [comment]
@tehkillerbee thank you! I tried with the Xavier Nx which is 8gb RAM and it worked. The steps you provided earlier were super useful. Did MMDeploy work for you for MMPOSE models? It works for MM Detection but I am yet to test it with MMPOSE. Please let me know if you had any success with that.

**Comment by tehkillerbee** [comment]
@RS00001 Great to hear! I have not tried mmpose models myself, so I cannot give any advice there.

**Comment by RunningLeon** [comment]
Closed due to age.
