### ISSUE TITLE
an error occurred while converting the onnx model using mmdeploy/tools/deploy.py，AttributeError: module 'mmcv' has no attribute 'Config'

### ISSUE THREAD

**Issue by likecv** [open-mmlab/mmdeploy#1956]
### Checklist

- [x] I have searched related issues but cannot get the expected help.
- [x] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [x] 3. The bug has not been fixed in the latest version.

### Describe the bug

an error occurred while converting the onnx model using mmdeploy/tools/deploy.py，AttributeError: module 'mmcv' has no attribute 'Config'

### Reproduction

an error occurred while converting the onnx model using mmdeploy/tools/deploy.py，AttributeError: module 'mmcv' has no attribute 'Config'

### Environment

```Shell
an error occurred while converting the onnx model using mmdeploy/tools/deploy.py，AttributeError: module 'mmcv' has no attribute 'Config'
```

### Error traceback

```Shell
an error occurred while converting the onnx model using mmdeploy/tools/deploy.py，AttributeError: module 'mmcv' has no attribute 'Config'
```

**Comment by irexyc** [comment]
Please check your environment.

MMDeploy master or tag v0.xx is target to original openmmlab algorithm repo and MMDeploy dev-1.x and tag v1.xx is target to newly openmmlab algorithm repo. 

Since you installed mmengine, I doubt you are using newly openmmlab algorithm repo, so you should use MMDeploy dev-1.x branch or tag v1.xx

**Comment by irexyc** [comment]
dumplicate of https://github.com/open-mmlab/mmdeploy/issues/1959
