### ISSUE TITLE
[Bug] The result of the mmpose with heatmap is wrong, and the problem appears to be due to a faulty decoder.

### ISSUE THREAD

**Issue by Runshi-Zhang** [open-mmlab/mmdeploy#2106]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

The rtmdet_m_8xb32-300e_coco_20220719_112220-229f527c.pth was converted to onnx for c++, and this code ran just fine. But the key point obtained by the network is wrong. Is it because decoding with heatmap is not supported in mmdeploy.

### Reproduction

The example named pose_detection.cpp was run.

### Environment

```Shell
mmdeploy 1.0.0
mmpose 1.0.0
```

**Comment by irexyc** [comment]
Could you please provide an image and results from pytorch and mmdeploy?

**Comment by Runshi-Zhang** [comment]
> Could you please provide an image and results from pytorch and mmdeploy?

The image size is 736 * 1024, and the result in c++ is :
1000.23 1019.86
960.331 872.664
-96.9156        397.609
-96.9156        -164.427
1093.32 -318.318
1106.62 -371.846
1066.72 -251.409
-150.11 -512.355
-150.11 -512.355
-96.9156        1013.17
-123.513        -485.591
-123.513        1066.7
2.82465 551.5
1020.18 1200.52
807.396 1200.52
-150.11 -512.355
-150.11 -512.355
In pytorch and mmdeploy, task_processor.visualize was added, then the result is true.

**Comment by irexyc** [comment]
@Runshi-Zhang 

Could you provide the image? Otherwise, I can't reproduce it.

**Comment by Runshi-Zhang** [comment]
![out](https://github.com/open-mmlab/mmdeploy/assets/94819508/f3e137c0-2309-4f74-9850-bc1515177d7d)

**Comment by Runshi-Zhang** [comment]
python mmdeploy/tools/deploy.py mmdeploy/configs/mmpose/pose-detection_onnxruntime_static.py mmpose/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-256x192.py td-hm_hrnet-w32_8xb64-210e_coco-256x192-81c58e40_20220909.pth img/out.jpg --work-dir mmdeploy_model/hrnet --device cpu --dump-info
The deploy config was not  modified.

**Comment by irexyc** [comment]
HI, @Runshi-Zhang ,

My convert command:
```python
python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmpose/pose-detection_onnxruntime_static.py \
    mmpose/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-256x192.py \
    https://download.openmmlab.com/mmpose/v1/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-256x192-81c58e40_20220909.pth \
    mmdeploy/demo/resources/human-pose.jpg \
    --work-dir /tmp/hrnet --device cpu --dump-info
```

For pose estimation, you should provide the human box. If you don't provide as [pose_detection.cpp](https://github.com/open-mmlab/mmdeploy/blob/main/demo/csrc/c/pose_detection.cpp#L35), it will take the full image as human box, the result won't be right.  You should use `mmdeploy_pose_detector_apply_bbox` instead of `mmdeploy_pose_detector_apply` for [pose api](https://github.com/open-mmlab/mmdeploy/blob/main/csrc/mmdeploy/apis/c/mmdeploy/pose_detector.h)

```
./bin/pose_detection cuda /tmp/hrnet 240165348-f3e137c0-2309-4f74-9850-bc1515177d7d.jpg
```

<img width="1628" alt="image" src="https://github.com/open-mmlab/mmdeploy/assets/16019484/1bb0cd8b-830d-4d71-8584-306ef0b7be5d">


Take the crop image as input:
```
./bin/pose_detection cuda /tmp/hrnet crop.jpg
```
<img width="1403" alt="image" src="https://github.com/open-mmlab/mmdeploy/assets/16019484/ed750dff-66f0-4194-a759-b3141b1e8820">

The negtive result is strange and I can't reproduct it.
