### ISSUE TITLE
[Bug] librknn_api.so: error adding symbols: File in wrong format

### ISSUE THREAD

**Issue by zhanghui-china** [open-mmlab/mmdeploy#2280]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

when i compile mmdeploy SDK:
execute:
cmake .. \
    -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/rknpu2-linux-gnu.cmake \
    -DMMDEPLOY_BUILD_SDK=ON \
    -DMMDEPLOY_TARGET_BACKENDS="rknn" \
    -DMMDEPLOY_BUILD_EXAMPLES=ON \
    -DOpenCV_DIR=${OpenCV_AARCH64_INSTALL_DIR}/lib/cmake/opencv4
make -j $(nproc) && make install

compile error!

### Reproduction

[ 79%] Built target mmdeploy_mmocr
Scanning dependencies of target mmdeploy
[ 80%] Linking CXX shared library ../../../../lib/libmmdeploy.so
/home/rock/rknpu2/runtime/RK3588/Linux/librknn_api/aarch64/librknn_api.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
csrc/mmdeploy/apis/c/CMakeFiles/mmdeploy.dir/build.make:156: recipe for target 'lib/libmmdeploy.so.1.2.0' failed
make[2]: *** [lib/libmmdeploy.so.1.2.0] Error 1
CMakeFiles/Makefile2:1673: recipe for target 'csrc/mmdeploy/apis/c/CMakeFiles/mmdeploy.dir/all' failed
make[1]: *** [csrc/mmdeploy/apis/c/CMakeFiles/mmdeploy.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

### Environment

```Shell
Ubuntu 18.04 LTS X86
gcc 7.5.0
conda python 3.8
MMDEPLOY_DIR=~/mmdeploy
ONNXRUNTIME_DIR=onnxruntime-linux-x64-1.8.1
LD_LIBRARY_PATH=$ONNXRUNTIME_DIR/lib:$LD_LIBRARY_PATH
pytorch 1.8.1
mmcv>=2.0.0rc2
rknn_toolkit2-1.5.0
numpy 1.20.3
```

**Comment by AllentDan** [comment]
Reference of https://www.quora.com/How-do-you-resolve-Gcc-error-adding-symbol-file-in-wrong-format-Linux-C-Ubuntu-GCC-development.

Kind of sounds like a mixed version error, and the entire project may need to be recompiled from scratch rather than doing an incremental compile/link.

This may be an error from the gcc cache structure for the project, and the compiler version changed…

Usually a “make clean” to delete all object files (if the option is provided in the Makefile) should fix this, and a following “make” will recompile everything.
