### ISSUE TITLE
[Bug] TensorRT visualization doesn't show correct custom labels as part of model conversion in tools/deploy.py

### ISSUE THREAD

**Issue by fujikosu** [open-mmlab/mmdeploy#2302]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I trained a custom model and ran tools/deploy.py with that pytorch model to get tensorRT model. As part of conversion, two visualization results were generated.
output_pytorch.jpg and output_tensorrt.jpg

In output_pytorch.jpg, the custom labels were correctly used but in output_tensorrt.jpg, coco labels were used instead. the bounding box locations looked exact same. The custom label's ids on the pytorch image and coco label's ids used on the tensorRT image matched so I think tensorrt model somehow failed to retrieve class names or doesn't include class names in the model side. But there was no warning or error in the log I pasted below.

How can we fix this and make tensorRT visualization result also use correct custom labele names?

### Reproduction

Run tools/deploy.py over non-COCO model that has custom labels and compare label names between output_pytorch.jpg and output_tensorrt.jpg

### Environment

```Shell
We used this environment below

FROM openmmlab/mmdeploy:ubuntu20.04-cuda11.3-mmdeploy0.14.0
RUN mim install mmdet==2.28.2
```

### Error traceback

```Shell
No warning regarding using COCO label names included in the log

2023-07-26 03:58:50,496 - mmdeploy - INFO - visualize tensorrt model start.
/usr/local/lib/python3.8/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
2023-07-26 03:58:53,284 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /root/workspace/mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
2023-07-26 03:58:53,285 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /root/workspace/mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
[07/26/2023-03:58:57] [TRT] [W] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.4.2
[07/26/2023-03:58:58] [TRT] [W] TensorRT was linked against cuDNN 8.2.1 but loaded cuDNN 8.2.0
[07/26/2023-03:58:58] [TRT] [W] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.4.2
[07/26/2023-03:58:58] [TRT] [W] TensorRT was linked against cuDNN 8.2.1 but loaded cuDNN 8.2.0
/usr/local/lib/python3.8/dist-packages/mmdet/datasets/utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
2023-07-26 03:58:58,664 - mmdeploy - WARNING - render and display result skipped for headless device, exception No module named 'tkinter'
2023-07-26 03:59:00,141 - mmdeploy - INFO - visualize tensorrt model success.
```

**Comment by irexyc** [comment]
The forward of tensorrt/pytorch model only output tensors (numbers) and doesn't have meta information.

Visualize process happens after model forward. I think the problem is the different of getting `CLASSES` between pytorch model and tensorrt model.

For pytorch model([init_pytorch_model](https://github.com/open-mmlab/mmdeploy/blob/0.x/mmdeploy/codebase/mmdet/deploy/object_detection.py#L82)), it use [init_detector](https://github.com/open-mmlab/mmdetection/blob/2.x/mmdet/apis/inference.py#L47-L48) to load model. The CLASSES are read from checkpoint.

For backend model([init_backend_model](https://github.com/open-mmlab/mmdeploy/blob/0.x/mmdeploy/codebase/mmdet/deploy/object_detection.py#L66)), it reads from [model config](https://github.com/open-mmlab/mmdeploy/blob/0.x/mmdeploy/codebase/mmdet/deploy/object_detection_model.py#L754)

You may check why backend failed to read `CLASSES`. The easyest workaround is assign the right `CLASSES` to the model created by init_backend_model. Or you can implement the visualize method own based on your datasets.

**Comment by fujikosu** [comment]
Thank you for the explanation! Our issue was in config side as you suggested. Closing this issue now
