### ISSUE TITLE
mmdeploy在jetson nano的环境配置字

### ISSUE THREAD

**Issue by yin-qiyu** [open-mmlab/mmdeploy#242]
jetson nano 环境
 jetpack：4.6
cuda：10.2
torch：1.8.0
torchvision：0.9.0

1.请问使用此仓库前需要先安装mmcv-full 嘛 。在安装mmcv时候Building wheel for mmcv-full (setup.py) 失败。
2. git submodule update --init --recursive 失败

**Comment by AllentDan** [comment]
Hi, could you please change the description language to English? 

1. Please post the error log so that we can analyze the reason. Maybe you forgot to do `sudo apt-get install libssl-dev` follow the [tutorial](https://mmdeploy.readthedocs.io/en/latest/tutorials/how_to_install_mmdeploy_on_jetsons.html#install-mmcv)?
2. Seems you should change the download source to inside ones.
