### ISSUE TITLE
ViT deploy's model outputs inconsistent test results every time.

### ISSUE THREAD

**Issue by royiluo** [open-mmlab/mmdeploy#510]
**Describe the bug**

I deployed Vision Transformer using mmdeploy and each time the exported model performs the test results, for the same input images, you can see that the classification results are different for both PyTorch and ONNX.

Here are the ‘output_onnxruntime.jpg’ and ‘output_pytorch.jpg’ after executing the below deployment script. You can see that all the classification results are incorrect.

![output_onnxruntime.jpg](https://user-images.githubusercontent.com/3327918/169766649-401d7f5b-1ab5-47d2-9e07-bcbe53aa4453.jpeg)
![output_pytorch.jpg](https://user-images.githubusercontent.com/3327918/169766659-1fb9b5e5-8aed-4d62-b0a4-42a9c02c75dc.jpeg)
![output_onnxruntime.jpg](https://user-images.githubusercontent.com/3327918/169766663-d7d1a4f5-3058-478e-9c6d-e7079b356656.jpeg)
![output_pytorch.jpg](https://user-images.githubusercontent.com/3327918/169766667-5368e572-4da6-4ec4-a576-626b574ef1dc.jpeg)

**Reproduction**

1. What command or script did you run?

Here is the deply script in docker: 
```none
#!/bin/bash

MMDEPLOY_DIR=/root/workspace/mmdeploy
MMCLS_DIR=/root/workspace/mmclassification
CHECKPOINT_DIR=/root/workspace/mmclassification/checkpoints/VisionTransformer/
INPUT_IMG=${MMCLS_DIR}/demo/demo.JPEG
WORK_DIR=/root/workspace/work_dirs


python ${MMDEPLOY_DIR}/tools/deploy.py \
    ${MMDEPLOY_DIR}/configs/mmcls/classification_onnxruntime_static.py \
    ${MMCLS_DIR}/configs/vision_transformer/vit-base-p16_ft-64xb64_in1k-384.py \
    ${CHECKPOINT_DIR}/vit-base-p16_3rdparty_pt-64xb64_in1k-224_20210928-02284250.pth \
    ${INPUT_IMG} \
    --work-dir ${WORK_DIR} \
    --device cpu
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
There is no modification to the config, it is used config file directly from the repo.

**Environment**

Use the container to run the mmdeploy directly from docker image build from repo: [Dockerfile](https://github.com/open-mmlab/mmdeploy/blob/master/docker/CPU/Dockerfile)

**Comment by tpoisonooo** [comment]
Let me try it with onnxruntime backend... 

With ncnn backend in [this PR](https://github.com/open-mmlab/mmdeploy/pull/403), everything is fine .

**Comment by tpoisonooo** [comment]
* mmcls>=0.21.0, ViT needs [`resize_pos_embed`](https://github.com/open-mmlab/mmclassification/blob/6beac5060f0c1d57141642dba77c19c9ed6b3873/mmcls/models/utils/embed.py#L14) 
* mmcv >=1.4.2, according to [mmcls installation doc](https://mmclassification.readthedocs.io/en/latest/install.html)

**Comment by tpoisonooo** [comment]
Can you give me the `mmdeploy` commit-id and  `mmcls` version ?  @royiluo

**Comment by royiluo** [comment]
'mmdeploy' commit-id:
commit 0cd44a6799ec168f885b4ef5b776fb135740487d (HEAD -> master, origin/master, origin/HEAD)
Author: hanrui1sensetime <[83800577+hanrui1sensetime@users.noreply.github.com](mailto:83800577%2Bhanrui1sensetime@users.noreply.github.com)>
Date:   Thu May 12 12:00:57 2022 +0800

'mmcls' version: 
0.23.0

**Comment by tpoisonooo** [comment]
I have tried these version set, still not reproduce the problem:

|mmcv|mmdeploy|mmcls|onnxruntime|MODEL_PATH
|-|-|-|-|-|
|1.4.8|https://github.com/open-mmlab/mmdeploy/commit/0cd44a6799ec168f885b4ef5b776fb135740487d|v0.23.0|1.8.1|[download](https://download.openmmlab.com/mmclassification/v0/vit/finetune/vit-base-p16_in21k-pre-3rdparty_ft-64xb64_in1k-384_20210928-98e8652b.pth)|

**Comment by tpoisonooo** [comment]
I cannot reproduce the problem after tried these 3 version sets:

|mmcv|mmdeploy|mmcls|onnxruntime|MODEL_PATH
|-|-|-|-|-|
|1.4.8|https://github.com/open-mmlab/mmdeploy/commit/0cd44a6799ec168f885b4ef5b776fb135740487d|v0.23.0|1.8.1|[download](https://download.openmmlab.com/mmclassification/v0/vit/finetune/vit-base-p16_in21k-pre-3rdparty_ft-64xb64_in1k-384_20210928-98e8652b.pth)|
|1.4.8|0cd44a6|v0.22.0|1.8.1|download|
|1.5.1|0cd44a6|v0.23.0|1.8.1|download|

Actually we can split the whole procedure into 3 parts and verify each one. Please make sure that the ** torch model not modified**.

## Verify onnxruntime
After `python3 tools/deploy.py xxxx`, you would found and `end2end.onnx` in `work_dir`. Please use `onnxruntime` to test the `.onnx` file. If the result is stable, try next one. Here is some sample code:

```Python
import cv2
import time
import numpy as np
import onnxruntime as rt
sess = rt.InferenceSession("end2end.onnx")

# read test image
img = cv2.imread("/path/to/DEMO.jpeg")
img = cv2.resize(img, (384, 384))
img_data = img[np.newaxis,:,:,:]

# inference
result = sess.run(["output"], {"input": img_data})
```

## Verify torch2onnx

`md5` or `md5sum` the `end2end.onnx`, make sure that converted model is the same.

In my envrionment, md5 value is always  the same. I think **there is no timestamp in .onnx** format:
```bash
$ python3 tools/deploy.py configs/mmcls/classification_onnxruntime_static.py ~/mmclassification/configs/vision_transformer/vit-base-p16_ft-64xb64_in1k-384.py  https://download.openmmlab.com/mmclassification/v0/vit/finetune/vit-base-p16_in21k-pre-3rdparty_ft-64xb64_in1k-384_20210928-98e8652b.pth   ~/mmclassification/demo/demo.JPEG    --work-dir vit --device cpu
...
$ md5sum vit/end2end.onnx
357ddb007a86407d2623f4bbf6ef8346  vit/end2end.onnx
```
with mmcls==0.23.0,mmcv==1.5.1,mmdeploy commit-id==0cd44a


## Verify onnxruntimeWrapper
Since mmdeploy use onnxruntime to inference, we can
`pdb`  [at  onnxruntime wrapper forward function](https://github.com/open-mmlab/mmdeploy/blob/de3f18fbb28ebec67d2382085c52d766056c1657/mmdeploy/backend/onnxruntime/wrapper.py#L76), make sure that all input/ouput is stable.

**Comment by royiluo** [comment]
You are verifying on the second stage [model](https://download.openmmlab.com/mmclassification/v0/vit/finetune/vit-base-p16_in21k-pre-3rdparty_ft-64xb64_in1k-384_20210928-98e8652b.pth), but I am verifying on the first stage [model](https://download.openmmlab.com/mmclassification/v0/vit/pretrain/vit-base-p16_3rdparty_pt-64xb64_in1k-224_20210928-02284250.pth). When I switched to the second stage model for validation, this inconsistency did not appear anymore.
