### ISSUE TITLE
Please tell me about how to do video inference faster

### ISSUE THREAD

**Issue by NJIMAMTO** [open-mmlab/mmdeploy#522]
Hi, thank you for answering my question the other day.

After the question, I was able to get to the point
where I could use `mmdeploy.apis.inference_model()`  and `mmcv.VideoReader()` to make inferences.
However, I am having problems with my goal of speeding up the video inference.

The inference speed is much slower than when using the MMDetection API.
To solve this problem, I also tried inference using TensorRT API, but it did not work.

Therefore, I would like to know if you know how to make it perform as it should.

**Comment by irexyc** [comment]
Since both use the same video decoder(opencv actually), The inference speed shouldn't vary too much.

You shouldn't use mmdeploy.apis.inference_model() to make inference.

You can check the code [here](https://github.com/open-mmlab/mmdeploy/blob/master/mmdeploy/apis/inference.py#L11-L51), it will init model every time you call this function which may cause the slow speed.

You may try to use in this way:
```python
# Some imports are omitted

deploy_cfg, model_cfg = load_config(deploy_cfg, model_cfg)
from mmdeploy.apis.utils import build_task_processor
task_processor = build_task_processor(model_cfg, deploy_cfg, device)

model = task_processor.init_backend_model(backend_files)
input_shape = get_input_shape(deploy_cfg)

video = mmcv.VideoReader('sample.mp4')

with torch.no_grad():
  for img in video:
    model_inputs, _ = task_processor.create_input(img, input_shape)
    result = task_processor.run_inference(model, model_inputs)
```

**Comment by NJIMAMTO** [comment]
@lvhan028 @irexyc 

Thank you both for your replies.

I have run the program you suggested and it has saved me a great deal of time.
Thank you very much.
