### ISSUE TITLE
how to specify backend for the c++ sdk demo

### ISSUE THREAD

**Issue by AllenDun** [open-mmlab/mmdeploy#583]
there are few docs for how to use c++ sdk

**Comment by lzhangzz** [comment]
Hi @AllenDun,

We recommand using the C API instead of C++ API. The C++ part consists of internal objects that is unstable. On the other hand we intend to keep the C API stable even if it's C++ counterpart changes.

As for your question in the title. Currently you don't need to specify backends when using the SDK, the backend for a model is baked into the model's metadata generated by the model converter. The SDK will load the backend accordingly.

**Comment by AllenDun** [comment]
Hi@lzhangzz, 
thanks for help. I understand it more. I want to know more about the details for the whole C API as well as the SDK. However, there are few docs or annotations in the source codes, it is not very easy to deeply understand. I will try it harder:)
