### ISSUE TITLE
unexpected key in source state_dict: rpn_head.rpn_conv.weight, rpn_head.rpn_conv.bias, rpn_head.rpn_cls.weight, rpn_head.rpn_cls.bias, rpn_head.rpn_reg.weight, rpn_head.rpn_reg.bias

### ISSUE THREAD

**Issue by Audrey528** [open-mmlab/mmdeploy#693]
I build env using the doc [Build for Linux-x86_64](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/linux-x86_64.md). When I run
```
python ${MMDEPLOY_DIR}/tools/deploy.py \
    ${MMDEPLOY_DIR}/configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py \
    ${MMDET_DIR}/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
    ${CHECKPOINT_DIR}/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    ${MMDET_DIR}/demo/demo.jpg \
    --work-dir ${WORK_DIR} \
    --device cuda:0 \
    --dump-info
```
I meet the question, I need some help, thanks very much.
![1656660396(1)](https://user-images.githubusercontent.com/68552295/176845840-b8995f56-9334-4b79-b92a-52b019b99c7c.png)

**Comment by irexyc** [comment]
Have you modified ${MMDET_DIR}/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py?

There have two wired thing:
1. the model and loaded static dict do not match.
2. data = test_pipeline(data) seems call LoadProposals but the original config don't contains this.

**Comment by Audrey528** [comment]
I don't modified ${MMDET_DIR}/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py.

**Comment by Audrey528** [comment]
@irexyc Thanks for your reply. I don't modified faster_rcnn_r50_fpn_1x_coco.py and I use the model loaded from the mmdetection github.

**Comment by irexyc** [comment]
@Audrey528 

I can't reproduce your problem. As you can see, the [faster_rcnn_r50_fpn_1x_coco.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py) use this [dataset config](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/datasets/coco_detection.py), and test pipeline is below(doesn't use LoadProposals).
```
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

```

While I guess the config you actually use is [fast_rcnn_r50_fpn_1x_coco.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/fast_rcnn/fast_rcnn_r50_fpn_1x_coco.py) because it contains 'LoadProposals' transform and the static dict mismatch problem can have a reasonable explaination.

Therefore, please make sure the model_cfg that you ues is right and rerun the command to check if the problem still exists.

**Comment by lvhan028** [comment]
> @irexyc Thanks for your reply. I don't modified faster_rcnn_r50_fpn_1x_coco.py and I use the model loaded from the mmdetection github.

Hi, @Audrey528 , could you post the result of `python mmdeploy/tools/check_env.py`?

**Comment by Audrey528** [comment]
@irexyc Thanks for your patience. Now It's ok. I use the same config file as you said. Now I don't change any file. But when I did other task, I uninstall opencv  using the command `sudo apt-get install libopencv-dev` to install and building from the source code.
 @lvhan028 I check my env. But a phenomenon is weird. The version of opencv built from the source code is 4.5.1, however the opencv shows 4.6.0.
![image](https://user-images.githubusercontent.com/68552295/179679341-3086d405-0932-448b-bbdb-fc21d4985175.png)

**Comment by lvhan028** [comment]
Here is how we get OpenCV version: 
```Python
import cv2
env_info['OpenCV'] = cv2.__version__
```
When you install mmcv-full, it will install the latest OpenCV-Python, which is 4.6.0.
