### ISSUE TITLE
CMake Error: The source directory "/root/workspace/mmdeploy/build/install/example" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by tcexeexe** [open-mmlab/mmdeploy#898]
Hi~
    l use the `sudo docker build docker/GPU/ -t mmdeploy:master-gpu --build-arg USE_SRC_INSIDE=true`to build the docker. But an error occurred that 
`CMake Error: The source directory "/root/workspace/mmdeploy/build/install/example" does not appear to contain CMakeLists.txt.`
<img width="720" alt="322d49629e6020b5ebc9a82da38a729" src="https://user-images.githubusercontent.com/28287196/184363888-27798d3c-a788-4d1c-b3f2-3b519ff633e2.png">
Is there any advice about this problem?
My enviroment is 
cuda11.1 

Driver Version: 470.141.03

nvidia-docker --version
Docker version 20.10.17, build 100c701

**Comment by tpoisonooo** [comment]
@lvhan028

**Comment by irexyc** [comment]
For now, you can manually modify the dockerfile accordng to https://github.com/open-mmlab/mmdeploy/pull/879/files

**Comment by tcexeexe** [comment]
> For now, you can manually modify the dockerfile accordng to https://github.com/open-mmlab/mmdeploy/pull/879/files

it seems that the doc is for windows, it's the modify of dockerFile of ubuntu can follow this guide?

**Comment by irexyc** [comment]
The error is because you use a older dockerfile which is not compatible with master branch.

It seems the error is this line: https://github.com/open-mmlab/mmdeploy/blob/v0.6.0/docker/GPU/Dockerfile#L91

The older structure of example folder is 
example
|---- CMakeLists.txt
|---- //.. other source file

The new structure of exmaple folder is 
exmaple
|----cpp
         | ---- CMakeLists.txt
         | ---- other source file

You should update your dockerfile or change that line to `cd install/example/cpp  && mkdir -p build && cd build &&\`

**Comment by lvhan028** [comment]
@tcexeexe have you tried the latest mmdeploy? It has been fixed in v0.7.0
